version: '3.7'

services:
  proftpd:
    # image: kibatic/proftpd
    build:
      context: ..
    network_mode: "host"
    restart: unless-stopped
    environment:
      FTP_LIST: "user1:pass1;user2:pass2"
      MASQUERADE_ADDRESS: "4.3.2.1"
        #      USERADD_OPTIONS: "-o --gid 33 --uid 33"
    volumes:
      - "./ddata/user1:/home/user1"
      - "./ddata/user2:/home/user2"
