sudo: required

services:
  - docker

before_install:
  - make build
  - make run-tls
  - make logs-for-5
  - docker ps -a # check it's running
  - sudo apt-get install lftp # to make a test ftp connection

script:
  - make test-bob-tls #
